### ISSUE TITLE
executing command

### ISSUE THREAD

**Issue by Clotic93** [nicollasricas/streamdeckvsc#1]
Hi cool that u made something like this. However when i installed it and past like editor.action.copyLinesDownAction Nothing happens with executing a command

**Comment by nicollasricas** [comment]
Hi,

- Have you installed the [VS code extension](https://marketplace.visualstudio.com/items?itemName=nicollasr.vscode-streamdeck)?

- The focused instance of VS code when you pressed the key was active?
![image](https://user-images.githubusercontent.com/7860985/67146173-7248e580-f256-11e9-99f2-e09c31cf3635.png)

- Was the stream deck connected but not active when you pressed? Try to focus another window and switch back to activate it and press again.

It seems that many people forget to install the VS Code extension.

**Comment by Clotic93** [comment]
Got it working juped the gun when reported it, Got it to work. Was the
extension.

Den lör 19 okt. 2019 kl 16:04 skrev Nicollas R. <notifications@github.com>:
