### ISSUE TITLE
JSON arguments not working for Execute Command?

### ISSUE THREAD

**Issue by fleps** [nicollasricas/streamdeckvsc#14]
Hi, great tool.
I have the extension installed and device connected / active, have many commands already working fine

I'm trying to use Execute Command to run a specific task immediately.
When we do this via VSCode keybinding.json, we have something like this
```
{
        "key": "alt+]",
        "command": "workbench.action.tasks.runTask",
        "args": "watcher"
}
```
"watcher" is the label/name of the task inside my tasks.json, and the VSCode keybind above works fine.

But when I setup the Execute Command for `workbench.action.tasks.runTask`, on the JSON arguments fields I've tried different arguments but doesn't work, it just sends the `workbench.action.tasks.runTask`, which will trigger the dropdown on VS Code to choose the task.

I tried `{"args": "watcher"}` and even `{"label" : "watcher"}` on the field, to no avail.

Any ideas if this is possible?
Thanks

**Comment by fleps** [comment]
Nevermind, just tested having only "watcher" inside the field and it worked. The example on the plugin interface confused me that the {} and key name was needed on this case.

**Comment by AlexisHartford** [comment]
Wait How to do this again i had it before but i had to factory Rest and Lost how to run Task i had a Comment i reply to once about how to do it but looks like its gone.
