### ISSUE TITLE
Can't connect to Stream Deck on M1 Mac mini

### ISSUE THREAD

**Issue by opeik** [nicollasricas/streamdeckvsc#4]
Hi there,

As the title suggests the VScode extension can't connect to the Stream Deck plugin. I suspect it's got something to do with Rosetta. 

Let me know what additional information I can provide.

**Comment by nicollasricas** [comment]
Hi,

Are you connected to SSH or WSL? [#4](https://github.com/nicollasricas/vscode-streamdeck/issues/4#issuecomment-674471109) If not please provide the plugin log and the extension output on vs code.

Plugin.log location:

> ~/Library/Application Support/com.elgato.StreamDeck/Plugins/com.nicollasr.streamdeckvsc.mac.sdPlugin/plugin.log

**Comment by opeik** [comment]
Ah, good catch. I didn't notice it was working locally since I'm usually SSH'd into another computer. I added the config in #4 and it worked!
