### ISSUE TITLE
VSC Icon too large?

### ISSUE THREAD

**Issue by wildapt01** [nicollasricas/streamdeckvsc#6]
Hi,

First, great job on this. It's been extremely helpful for my work.

Now, the provided PNG image is quite large and at times is visually impairing the title readability.

Here is a different PNG which leaves more space for the title while keeping the VSC logo visible:

![VSC_topLeft](https://user-images.githubusercontent.com/14893362/116884028-43098780-abf4-11eb-8dce-1d1e8fe95109.png)

If you decide to add it to your project, please add me as collaborator. It'd be much appreciated.

**Comment by nicollasricas** [comment]
Hey,

Which logo are you referring to? plugin (Stream Deck), extension (vscode) or the actions default background?

Are you using the macOS version?

**Comment by wildapt01** [comment]
Hi Nicollas,

I'm on PC.

The file I'm referring to is the background icon [here](streamdeckvsc/StreamDeckVSC/Images/VisualStudioCode.png
).

**Comment by nicollasricas** [comment]
![image](https://user-images.githubusercontent.com/7860985/117180678-6d994300-ada2-11eb-8a1f-e7c1e7c29f5e.png)

I like that idea, thank you for suggesting it. There's no need to add you as a collaborator, you can create a pull request then I will merge it or if it's easy for you just add the updated images here so I update myself (credits will be granted).

We need a 20px by 20px and an alternative version 40px by 40px, transparent background.

**Comment by wildapt01** [comment]
I'll do a pull request with the 2 options on transparent background.
