### ISSUE TITLE
Not working on brand new install of VSC

### ISSUE THREAD

**Issue by KensonPlayz** [nicollasricas/streamdeckvsc#7]
The only extension I have is this plugin, no others. For some reason nothing happens when I try Insert Snippet and put in say... 'doc'.

**Comment by nicollasricas** [comment]
If you were connected then you are using the snippet prefix and not the name.

What extension provided the snippet definition?

Take a look at this [example](https://github.com/nicollasricas/streamdeckvsc/issues/5#issuecomment-807519501), let me know if it works.

**Comment by KensonPlayz** [comment]
I believe it was built in, "Emmet Abbreviation" is what it says. Type some letters, press tab and it inserts it. I'm attempting this in HTML.
(new to taking courses, so I'm not super experienced with it yet)

**Comment by nicollasricas** [comment]
if you are typing then pressing TAB in most cases will be the snippet prefix, not the name.

```csharp
{
  "For Loop": { // SNIPPET NAME - THIS IS THE ONE YOU SHOULD USE WITH THE STREAM DECK ACTION
    "prefix": ["for", "for-const"] // SNIPPET PREFIX - THIS IS THE ONE YOU TYPE IN VSCODE THEN PRESS TAB...
    "body": ["for (const ${2:element} of ${1:array}) {", "\t$0", "}"],
    "description": "A for loop."
  }
}
```

Unfortunately, I couldn't find a way to insert snippets by their prefix only by name.

**Comment by KensonPlayz** [comment]
Hmm, would there be a way to use it to insert "doc" or "p" for pre-filling paragraphs, starting a new doc, etc? Or should I just use the built-in "Text" option with a multi-action and insert a Tab after?

Not sure what I'd use this plugin for, since I'd most likely use it to shorten the time it takes to create files.

**Comment by nicollasricas** [comment]
Emmet abbreviations are not defined as snippet by "contributions" they are provided by [code](https://github.com/microsoft/vscode/blob/main/extensions/emmet/package.json), so you can't use the Insert Snippet Action.

The best way to accomplish this is to create multiple actions as you said.

> Not sure what I'd use this plugin for, since I'd most likely use it to shorten the time it takes to create files.

In general, you can use it to execute any command provided by vs code or an extension and execute terminal commands.

I've been using the Insert Snippet action with my custom snippets, which is the code I repeat almost every day, so with a simple action press, I get 15-20 lines of repeating code.

I will close this, for now, let me know if you need more help.
