### ISSUE TITLE
Broken with newest Stream Deck version 5.1.2 on macOS

### ISSUE THREAD

**Issue by vincentschroeder** [nicollasricas/streamdeckvsc#8]
![image](https://user-images.githubusercontent.com/6410444/138432976-2e16d0b5-eef7-4300-a257-126a4c3be3d7.png)
Unfortunately, after updating to the newest version the plugin isn't sending events to vscode. The Vscode plugin says "connected" so there it seems to be okay.
![image](https://user-images.githubusercontent.com/6410444/138433203-cc10028c-221c-40ea-aea5-b86c1a629b6f.png)

**Comment by nicollasricas** [comment]
Hey, 

Try to click on the status bar item or switch tabs to force the activation process.

If still not working, paste the extension output here.

![image](https://user-images.githubusercontent.com/7860985/138454653-0e00f278-c297-45b2-801c-b27f4d5981d2.png)

**Comment by vincentschroeder** [comment]
Thanks is working now
